# Generated by Django 6.0.3 on 2026-03-26 19:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название организации')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=13, verbose_name='ОГРН')),
                ('address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Контактное лицо')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер договора')),
                ('contract_type', models.CharField(choices=[('contract', 'Договор'), ('subcontract', 'Договор подряда'), ('contract_work', 'Контракт')], max_length=20, verbose_name='Вид договора')),
                ('date', models.DateField(verbose_name='Дата договора')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма договора')),
                ('work_type', models.CharField(choices=[('land_survey', 'Межевой план'), ('technical_plan', 'Технический план'), ('kp_diagram', 'Схема на КПТ')], max_length=20, verbose_name='Вид работ')),
                ('address', models.TextField(verbose_name='Адрес объекта работ')),
                ('notification', models.TextField(blank=True, verbose_name='Извещение')),
                ('status', models.CharField(choices=[('in_progress', 'В работе'), ('completed', 'Выполнено'), ('finished', 'Завершено'), ('suspended', 'Приостановлено')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('relax', 'Расслабься'), ('normal', 'Нормальный'), ('urgent', 'Срочный'), ('critical', 'Критический')], default='normal', max_length=20, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='contracts.customer', verbose_name='Заказчик')),
                ('cadastral_engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadastral_contracts', to='contracts.employee', verbose_name='Кадастровый инженер')),
                ('designer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designer_contracts', to='contracts.employee', verbose_name='Оформление')),
                ('geodesist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geodesist_contracts', to='contracts.employee', verbose_name='Геодезист')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalContract',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=50, verbose_name='Номер договора')),
                ('contract_type', models.CharField(choices=[('contract', 'Договор'), ('subcontract', 'Договор подряда'), ('contract_work', 'Контракт')], max_length=20, verbose_name='Вид договора')),
                ('date', models.DateField(verbose_name='Дата договора')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма договора')),
                ('work_type', models.CharField(choices=[('land_survey', 'Межевой план'), ('technical_plan', 'Технический план'), ('kp_diagram', 'Схема на КПТ')], max_length=20, verbose_name='Вид работ')),
                ('address', models.TextField(verbose_name='Адрес объекта работ')),
                ('notification', models.TextField(blank=True, verbose_name='Извещение')),
                ('status', models.CharField(choices=[('in_progress', 'В работе'), ('completed', 'Выполнено'), ('finished', 'Завершено'), ('suspended', 'Приостановлено')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('relax', 'Расслабься'), ('normal', 'Нормальный'), ('urgent', 'Срочный'), ('critical', 'Критический')], default='normal', max_length=20, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Изменён')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cadastral_engineer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contracts.employee', verbose_name='Кадастровый инженер')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contracts.customer', verbose_name='Заказчик')),
                ('designer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contracts.employee', verbose_name='Оформление')),
                ('geodesist', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contracts.employee', verbose_name='Геодезист')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Договор',
                'verbose_name_plural': 'historical Договоры',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
