# Generated by Django 6.0.3 on 2026-04-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='work_description',
            field=models.CharField(blank=True, choices=[('clarification', 'Уточнение'), ('formation', 'Образование'), ('division', 'Раздел'), ('consolidation', 'Объединение'), ('redistribution', 'Перераспределение'), ('allocation', 'Выдел')], max_length=50, null=True, verbose_name='Описание работ'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='work_description',
            field=models.CharField(blank=True, choices=[('clarification', 'Уточнение'), ('formation', 'Образование'), ('division', 'Раздел'), ('consolidation', 'Объединение'), ('redistribution', 'Перераспределение'), ('allocation', 'Выдел')], max_length=50, null=True, verbose_name='Описание работ'),
        ),
    ]
