# Generated by Django 6.0.3 on 2026-04-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_work_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='note',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='contract',
            name='note_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания примечания'),
        ),
        migrations.AddField(
            model_name='contract',
            name='note_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления примечания'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='note',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='note_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания примечания'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='note_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления примечания'),
        ),
    ]
